# Funding options for solana-repo-scanner
# This file enables the "Sponsor" button on GitHub

# GitHub Sponsors (add your username when you set it up)
github: [Momo111psy]

# Other funding platforms
custom: ['https://github.com/Momo111psy/solana-repo-scanner']
